schema:
  - 'https://h4c-api.rabbithole.carrotly.tech/graphql'
documents:
  - './**/*.graphql'
generates:
  ./api/__generated__/graphql.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo